    Семинар 20.09

In [1]:
import numpy as np

In [22]:
a=np.arange(16).reshape(8,2)
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [23]:
print(a.T[:])
print(a.T[:,::2])
print(np.sum(a,axis=1))

[[ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]]
[ 1  5  9 13 17 21 25 29]


In [24]:
print(np.median(a))
print(np.sqrt(-1+0j))

7.5
1j


In [29]:
a=np.random.rand(10)

In [30]:
a

array([0.31715525, 0.09200136, 0.86570089, 0.11937728, 0.53082094,
       0.62349294, 0.81042708, 0.80292873, 0.79534743, 0.06761542])

In [31]:
a.sort()
a

array([0.06761542, 0.09200136, 0.11937728, 0.31715525, 0.53082094,
       0.62349294, 0.79534743, 0.80292873, 0.81042708, 0.86570089])

In [33]:
i=np.searchsorted(a,2)
i

10

In [34]:
import json

In [36]:
d={
    'kotek':{
        'fluffy': 'a lot',
        'quantity': 1
    },
    'pes':{
        'mass':1
    }  
}

In [39]:
import pprint
pprint.pprint(d)

{'kotek': {'fluffy': 'a lot', 'quantity': 1}, 'pes': {'mass': 1}}


In [38]:
s=json.dumps(d)
s

'{"kotek": {"fluffy": "a lot", "quantity": 1}, "pes": {"mass": 1}}'

In [57]:
from scipy.io import netcdf

with netcdf.netcdf_file('tos_O1_2001-2002.nc') as file:
    print(file)
    print(file.dimensions)
    print(file.variables['lon'].units)
    print(file.variables['tos'].dimensions)
    print(file.dimensions)

OrderedDict([('lon', 180), ('lat', 170), ('time', None), ('bnds', 2)])
b'degrees_east'
('time', 'lat', 'lon')
OrderedDict([('lon', 180), ('lat', 170), ('time', None), ('bnds', 2)])
